# Generated by Django 6.0.2 on 2026-02-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_remove_aluno_curso'),
        ('curso', '0002_curso_professor'),
        ('matricula', '0002_alter_matricula_data_matricula'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'curso'), name='unique_matricula_aluno_curso'),
        ),
    ]
