# Generated by Django 6.0.2 on 2026-02-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_email'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='curso.curso'),
            preserve_default=False,
        ),
    ]
