# Generated by Django 6.0.2 on 2026-02-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_aluno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
