# Generated by Django 6.0.2 on 2026-02-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_aluno_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='curso',
        ),
    ]
